name: Build and Test Modules

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Config Script
        run: |
          cd scripts
          chmod +x config.sh
          ./config.sh
        shell: bash

      - name: Create Build Directory
        run: |
          cd sniffer-mod
          mkdir build
        shell: bash

      - name: Build with CMake
        run: |
          cd sniffer-mod/build
          cmake ..
          make
        shell: bash

      - name: Run C++ Tests
        run: |
          cd sniffer-mod/build
          ./tests
        shell: bash

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' 

      - name: Run Go Tests
        run: |
          cd src-go
          go test ./tests/...
        shell: bash

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install Python Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r ai-mod/requirements.txt
        shell: bash

      - name: Run Python Tests
        run: |
          source .venv/bin/activate
          pytest ai-mod/src/tests
        shell: bash
